---
- include: "{{ item }}"
  with_first_found:
    - files:
        - _packages.yml
        - _config.yml
      skip: true
# https://stackoverflow.com/questions/28119521/ansible-include-task-only-if-file-exists
